# all workflows
workflows:
  - name: main
    rules: []
    stages:
      - name: build
        actions:
          - id: central/go-build
            config:
              # cross-platform build
              platform:
                - goos: windows
                  goarch: amd64
                - goos: linux
                  goarch: amd64
                - goos: darwin
                  goarch: amd64
          - id: central/java-build
          - id: central/python-build
          - id: central/node-build
          - id: central/hugo-build
          - id: central/helm-build
          - id: central/mkdocs-build
          - id: central/techdocs-build
      - name: test
        actions:
          - id: central/go-test
          - id: central/java-test
          - id: central/helm-test
      - name: package
        actions:
          - id: central/upx-optimize
          - id: central/buildah-build
            config:
              no-cache: false
              squash: true
              rebuild: true
      - name: lint
        actions:
          - id: central/go-lint-golangci
          - id: central/python-lint
          - id: central/helm-lint
      - name: scan
        actions:
          - id: central/gitleaks-scan
          - id: central/semgrep-scan
          #- id: central/fossa-source-scan
          - id: central/sonarqube-scan
      - name: report
        actions:
          - id: central/syft-container-sbom
          - id: central/grype-scan-sbom
          - id: central/repo-changelog-generate
            config:
              # changelog generator configuration
              templates:
                - github.changelog
                - discord.changelog
              commit_pattern:
                - (?P<type>[A-Za-z]+)((?:\((?P<scope>[^()\r\n]*)\)|\()?(?P<breaking>!)?)(:\s?(?P<subject>.*))?
              title_maps:
                build: "Build System"
                ci: "CI"
                docs: "Documentation"
                feat: "Features"
                fix: "Bug Fixes"
                perf: "Performance"
                refactor: "Refactor"
                style: "Style"
                test: "Test"
                chore: "Internal"
              note_keywords:
                - keyword: NOTE
                  title: Notes
                - keyword: BREAKING CHANGE
                  title: Breaking Changes
      - name: publish
        actions:
          - id: central/buildah-publish
          - id: central/helm-publish-nexus
          - id: central/techdocs-publish
          #- id: central/repo-tag-create
          #- id: central/repo-release-github
          #- id: central/java-publish
